const cart=JSON.parse(localStorage.getItem("nutrifreshCart")||"{}");
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("year").textContent=new Date().getFullYear();const d=document.getElementById("date");const t=new Date();t.setDate(t.getDate()+1);d.min=t.toISOString().slice(0,10);render()});
function save(){localStorage.setItem("nutrifreshCart",JSON.stringify(cart))}
function add(btn){const c=btn.closest(".product"),n=c.dataset.name,p=+c.dataset.price;cart[n]??={price:p,qty:0};cart[n].qty++;save();render();toast(n+" added to your order");document.getElementById("order").scrollIntoView({behavior:"smooth"})}
function qty(n,a){if(!cart[n])return;cart[n].qty+=a;if(cart[n].qty<1)delete cart[n];save();render()}
function clearCart(){Object.keys(cart).forEach(k=>delete cart[k]);save();render()}
function render(){const box=document.getElementById("items"),total=document.getElementById("total"),note=document.getElementById("threshold"),es=Object.entries(cart);if(!es.length){box.innerHTML='<p class="empty">No items added yet. Choose something from the menu.</p>';total.textContent="₹0";note.textContent="Minimum qualifying gym/group order: ₹199 for free delivery.";return}let sum=0;box.innerHTML=es.map(([n,x])=>{const line=x.price*x.qty;sum+=line;const safe=n.replaceAll("'","\\'");return `<div class="cart-row"><div><b>${n}</b><br>₹${x.price} × ${x.qty}</div><div class="cart-controls"><button type="button" onclick="qty('${safe}',-1)">−</button><span>${x.qty}</span><button type="button" onclick="qty('${safe}',1)">+</button><b>₹${line}</b></div></div>`}).join("");total.textContent="₹"+sum;note.textContent=sum>=199?"✓ Your order meets the ₹199 qualifying threshold for free gym/group delivery.":`Add ₹${199-sum} more to reach the ₹199 qualifying threshold for free gym/group delivery.`}
function submitOrder(e){e.preventDefault();const sum=Object.values(cart).reduce((a,x)=>a+x.price*x.qty,0);if(!sum){toast("Please add an item first.");return}const phone=document.getElementById("phone").value.replace(/\D/g,"");if(phone.length<10){toast("Please enter a valid mobile number.");return}const order={name:document.getElementById("name").value,phone,gym:document.getElementById("gym").value,address:document.getElementById("address").value,date:document.getElementById("date").value,slot:document.getElementById("slot").value,items:cart,total:sum};localStorage.setItem("nutrifreshLastOrder",JSON.stringify(order));toast("Order saved. Connect Razorpay to activate payment.")}
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2800)}
